config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  root 'home#index'
  resources :courses do
    resources :lessons
  end
  resources :users, only: [:index, :edit, :show, :update]
  get "static_pages/landing_page"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get 'home/activity'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        ©
        = Time.now.year
        ol.sa Udemy Course
        .row
        .fa.fa-envelope
        = mail_to 'saenko.oleg1993@gmail.com'
        .row
      .col-md-4
        = link_to 'Privacy Policy', privacy_policy_path
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on CoursePlatform', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "/"}
    /= image_tag 'logo.png', size: '20x20', alt: "logo", class: 'rounded'
    .fa.fa-graduation-cap
    Corserdemy
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.me-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.graduation-cap
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(enrollments_path)}"}
          = link_to enrollments_path, class: 'nav-link' do
            .fa.fa-lock-open
            Enrollments

      %ul.navbar-nav.ms-auto
        /SEARCH IN NAVBAR
        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          .input-group
            = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
            %button#button-addon2.btn.btn-primary{:type => "submit"}
              %span.fa.fa-search{"aria-hidden" => "true"}
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(home_activity_path)}"}
          = link_to home_activity_path, class: 'nav-link' do
            .fa.fa-bell
            Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.username
          .dropdown-menu.dropdown-menu-end{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav.ms-auto
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert closable alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.btn-close{"aria-hidden" => "true", "data-bs-dismiss" => "alert", :type => "button", :class => "float-end"}
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = content_for?(:title) ? yield(:title) : "Courserdemy"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br
    .bg-dark.text-white
    = render 'layouts/footer'